### ISSUE TITLE
Add some time-invariant fixed fields into the c3s-cmip6 inventory

### ISSUE THREAD

**Issue by agstephens** [roocs/roocs-utils#46]
* roocs-utils version: *
* Python version: 3.7+
* Operating System: *

### Description

We want to add some example time-invariant fixed variables into our c3s-cmip6 inventory.

Please find one or two datasets to add, using any of these variables:

["areacella", "areacello", "mrsofc", "sftlf", "sftof", "sftgif",  "orog" ]

You can search for them using Alan's CREPP web-interface, e.g.:

https://ppln.ceda.ac.uk/datasets_table/?Configuration=&Replica=&Withdrawn=&Paused=&Processing+Status=&Chain=&Has+active+task=&Do+not+delete=&Last+event+process+stage=&Name=orog&Name_type=substr&Requester=&Requester_type=substr&sort=Name+%28asc%29&per_page=5&action=view_table

Please make sure the relevant variable is related to existing experiment/records already included in our current inventory.

For these records, in the inventory, `time` should be set as: `time: undefined`

**Comment by ellesmith88** [comment]
2 example entries I have added look like this:
```
- path: ScenarioMIP/MIROC/MIROC6/ssp119/r1i1p1f1/Ofx/sftof/gn/v20190807
  ds_id: c3s-cmip6.ScenarioMIP.MIROC.MIROC6.ssp119.r1i1p1f1.Ofx.sftof.gn.v20190807
  var_id: sftof
  array_dims: y x
  array_shape: 256 360
  time: undefined
  latitude: -88.00 89.75
  longitude: 0.02 359.97
  size: 4069827
  size_gb: 0.0
  file_count: 1
  facets:
    mip_era: c3s-cmip6
    activity_id: ScenarioMIP
    institution_id: MIROC
    source_id: MIROC6
    experiment_id: ssp119
    member_id: r1i1p1f1
    table_id: Ofx
    variable_id: sftof
    grid_label: gn
    version: v20190807
  files:
  - sftof_Ofx_MIROC6_ssp119_r1i1p1f1_gn.nc

- path: ScenarioMIP/IPSL/IPSL-CM6A-LR/ssp119/r1i1p1f1/fx/mrsofc/gr/v20190410
  ds_id: c3s-cmip6.ScenarioMIP.IPSL.IPSL-CM6A-LR.ssp119.r1i1p1f1.fx.mrsofc.gr.v20190410
  var_id: mrsofc
  array_dims: lat lon
  array_shape: 143 144
  time: undefined
  latitude: -90.00 90.00
  longitude: 0.00 357.50
  size: 83516
  size_gb: 0.0
  file_count: 1
  facets:
    mip_era: c3s-cmip6
    activity_id: ScenarioMIP
    institution_id: IPSL
    source_id: IPSL-CM6A-LR
    experiment_id: ssp119
    member_id: r1i1p1f1
    table_id: fx
    variable_id: mrsofc
    grid_label: gr
    version: v20190410
  files:
  - mrsofc_fx_IPSL-CM6A-LR_ssp119_r1i1p1f1_gr.nc
 ```
